[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm run install:client']

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'npm run install:server && cd server && npm start' 