[build]
builder = "nixpacks"
buildCommand = "npm run install:client && cd client && npm run build"

[deploy]
startCommand = "npm run install:server && cd server && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.railway]
name = "ai-allstars" 